# Generated by Django 4.2.7 on 2023-12-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskModel',
            new_name='Task',
        ),
    ]
