# Generated by Django 4.2.7 on 2023-12-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_taskcategory_tasks'),
        ('task', '0002_rename_taskmodel_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ManyToManyField(to='category.taskcategory'),
        ),
    ]
