# Generated by Django 4.2.7 on 2023-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeModelForm',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
